name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444



    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.9'

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup npm
      run:
        npm install
        npm run install

    - name: building project
      run: npm run build

    - name: Run server
      run: npm run start:dev

    - name: Run tests
      run: pytest
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: 123456
        DB_NAME: postgres
        JWT_ACCESS_SECRET: F57cdRCyYNKLTXt3qCuJ
        JWT_REFRESH_SECRET: KyJLbjwriPv7Df7qdzDT
        GIGACHAT_AUTHORIZATION_KEY: MDE5YTM5NDctNGYyNC03MjZhLWFmNDktMTk1MjIzMTE3M2RiOmM2YTEwNzQ5LWQ3MzItNDBjZS04MjZkLTI4MDhkNjExOWNjMQ==
        FRONTEND_ORIGIN: http://localhost:3000
